name: Deploy Terraform Configuration

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: "1.2.0"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: "ckad-practice-420508"
        export_default_credentials: true

    - name: Set up credentials
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > gcp-key.json
        echo "gcp_credentials_file=gcp-key.json" >> $GITHUB_ENV

    - name: List files for debugging
      run: ls -l

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

